Add translation for 2.1
devmanorg/power_searching_with_google_rus pull request #15
Opened 2018-02-24 23:43 UTC by voron434

2018-02-25 06:07 UTC, Melevir requested changes
Текст сейчас очень сложно читать: в нём куча кальки с английского. Пройдись ещё раз по плану работы с текстом, плиз (описан в ридми).

2018-02-25 15:19 UTC, voron434 commented
Моя знакомая знимается переводом и ей тоже захотелось попробовать.
Настояла чтобы я отправил просто чтобы кто-то посмотрел.

2018-02-25 15:45 UTC, Melevir commented
Да не проблема. Я в ридми описал алгоритм, который должен помочь с очеловечиванием переводов. Там есть пара божественных пунктов, вроде чтения вслух, они прям очень помогают по моему опыту.
Если знакомая захочет поболтать/обсудить/посоветовать – сведи нас в тг :)

2018-03-08 21:49 UTC, voron434 commented
Ещё раз попробовал очеловечить.
Нужно учиться писать как люди...

2018-03-09 05:23 UTC, merged

2018-03-09 05:27 UTC, Melevir commented
Замерджил, но выглядит сложновато. Вот, например, первый абзац:

>Google действительно хорош не только в поиске информации, но и в поиске дополнительной информации, которая поможет вам правильнее сформулировать запрос. Эта дополнительная информация может быть невероятно полезной. Как вы можете видеть, иногда результаты поиска дают вам немного больше, чем вы просили. Действительно, слева, как обычно, синие ссылки, но здесь, с правой стороны у нас есть то, что называется панелью знаний

Если его прочитать вслух, то понятно, что он слишком сложный: так люди не говорят (особенно последнее предложение, там полная беда с запятыми). Бери и переделывай, пока не будет звучать вслух естественно. Вот что у меня получилось (это первый подход, можно лучше):

> С помощью Google можно найти информацию, которая поможет сформировать исходный поисковый запрос. Иногда в результатах поиска показывается не только обычные ссылки, но и дополнительная информация. На скриншоте в правом столбце показан пример панели знаний.

Да, с переводом можно обходиться довольно вольно. Главное – чтобы вся инфа была на месте.